apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      tolerations:
      # Tolerate all taints for observability
      - operator: "Exists"
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.userGroup }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - name: metrics
          containerPort: {{ .Values.port }}
        args:
        - 'prometheus'
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: root
          mountPath: /rootfs
          readOnly: true
      volumes:
      - name: root
        hostPath:
          path: /
      serviceAccountName: {{ .Chart.Name }}
