apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.name }}
  labels:
    app.kubernetes.io/name: {{ .Release.name }}  
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'hostPath'
  hostPID: true
  hostIPC: true
