apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    prometheus.io/port: "{{ .Values.port  }}"
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: {{ .Values.port }}
    name: metrics
    targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
